name: Build

# Run this workflow every time a new commit pushed to your repository
on: [push]

jobs:


  tags:
    name: Identify tags
    runs-on: ubuntu-latest
    outputs:
      git_tag: ${{ steps.get_tags.outputs.git_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2    
    
      - name: Identify git tags
        id: get_tags
        run: |
          git fetch --prune --unshallow --tags
          git_tag=`git describe --tags --abbrev=0`
          echo $git_tag
          echo "::set-output name=git_tag::$git_tag"

          


  release:
    name: Create single release for all builds
    runs-on: ubuntu-latest
    needs: tags
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create a release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{needs.tags.outputs.git_tag}}
          release_name: Release ${{needs.tags.outputs.git_tag}} 
          draft: true
          prerelease: true


  build_windows:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    needs: [release, tags]
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows 2016 MSVC 2017",
            os: windows-2016,
            build_type: "Release",
            cc: "cl",
            cxx: "cl"
          }   


    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Qt
        uses: jurplel/install-qt-action@v2          

      - name: Prepare Visual Studio
        if: startsWith(matrix.config.os, 'windows')
        uses: ilammy/msvc-dev-cmd@v1
        with:
          sdk: 10.0.10240.0
          

          
      - name: Environment Checking
        shell: powershell
        run: |
          Get-ChildItem Env:PATH          
          echo $PSScriptRoot
          $Env:PATH = $Env:PATH + ';D:\a\Konclude\Qt\5.15.2\msvc2019_64\bin'
          $Env:PATH = $Env:PATH + ';$PSScriptRoot\External\vcpkg\Windows\x64\bin'
          $Env:PATH = $Env:PATH + ';.\External\vcpkg\Windows\x64\bin'
          Get-ChildItem Env:PATH
          
      - name: Install Windows 8.1 SDK
        shell: powershell
        run: |
          Invoke-WebRequest -Method Get -Uri https://go.microsoft.com/fwlink/p/?LinkId=323507 -OutFile sdksetup.exe -UseBasicParsing
          Start-Process -Wait sdksetup.exe -ArgumentList "/q", "/norestart", "/features", "OptionId.WindowsDesktopSoftwareDevelopmentKit", "OptionId.NetFxSoftwareDevelopmentKit"          


      - name: Compile Windows        
        if: startsWith(matrix.config.os, 'windows')
        run: |
          msbuild Konclude-VS15.sln /p:Configuration=Release /p:Platform="Win64"


      - name: Prepare Windows Execution
        if: startsWith(matrix.config.os, 'windows')
        run: |
          Copy-Item ".\External\vcpkg\Windows\x64\bin\*" -Destination "."
          dir
          dir D:\a\Konclude\Qt\5.15.2\msvc2019_64\bin


      - name: Upload
        uses: actions/upload-artifact@v2
        if: startsWith(matrix.config.os, 'windows')  
        with:
          name: Konclude-compiled-windows
          path: x64\Release\VS2015\Konclude.exe

          

      - name: Create Konclude Release
        run: | 
          $ROOT="$(pwd)"   
          $revisionCount="966"
          $revisionTagName="v0.6.2"
          $revisionHashName="fa20b125"
          mkdir Release          
          
          $BUILD_DIR=$ROOT
          $PROJ=$ROOT
          $RELEA="$ROOT\Release\Konclude-$revisionTagName-$revisionCount-Windows-x64-MSVC-Dynamic-Qt5.15.2"
          
          mkdir $RELEA
          mkdir "$RELEA/Configs"
          mkdir "$RELEA/Tests"
          mkdir "$RELEA/Binaries"
          
          cd $BUILD_DIR
          copy "$BUILD_DIR\x64\Release\VS2015\Konclude.exe" "$RELEA/Binaries"
          
          copy "$PROJ\LGPL-3.0.txt" "$RELEA"
          copy "$PROJ\GPL.txt" "$RELEA"
          copy "$PROJ\Readme.md" "$RELEA"
          copy "$PROJ\Tests\1b-satisfiability-request.xml" "$RELEA/Tests"
          copy "$PROJ\Tests\galen.owl.xml" "$RELEA/Tests"
          copy "$PROJ\Tests\galen-classify-request.xml" "$RELEA/Tests"
          copy "$PROJ\Tests\roberts-family-full-D.owl.xml" "$RELEA/Tests"
          copy "$PROJ\Tests\roberts-family-full-D-classify-realize-request.xml" "$RELEA/Tests"
          copy "$PROJ\Tests\lubm-univ-bench.owl.xml" "$RELEA/Tests"
          copy "$PROJ\Tests\lubm-univ-bench-data-1.ttl" "$RELEA/Tests"
          copy "$PROJ\Tests\lubm-univ-bench-sparql-load-and-query-test.sparql" "$RELEA/Tests"
          copy "$PROJ\Tests\lubm-univ-bench-sparql-load-and-complex-query-rasqal-test.sparql" "$RELEA/Tests"
          copy "$PROJ\Tests\roberts-family-full-sparql-existential-variables-query-test.sparql" "$RELEA/Tests"
          copy "$PROJ\Tests\test-request.xml" "$RELEA/Tests"
          copy "$PROJ\Scripts\Konclude.bat" "$RELEA"
          copy "$PROJ\Configs\default-config.xml" "$RELEA/Configs"
          copy "$PROJ\Configs\querying-config.xml" "$RELEA/Configs"          
          
          copy ".\External\vcpkg\Windows\x64\bin\*.dll" "$RELEA/Binaries" 
          copy "D:\a\Konclude\Qt\5.15.2\msvc2019_64\bin\Qt5Core.dll" "$RELEA/Binaries" 
          copy "D:\a\Konclude\Qt\5.15.2\msvc2019_64\bin\Qt5Gui.dll" "$RELEA/Binaries" 
          copy "D:\a\Konclude\Qt\5.15.2\msvc2019_64\bin\Qt5Network.dll" "$RELEA/Binaries" 
          copy "D:\a\Konclude\Qt\5.15.2\msvc2019_64\bin\Qt5Concurrent.dll" "$RELEA/Binaries" 
          copy "D:\a\Konclude\Qt\5.15.2\msvc2019_64\bin\Qt5Xml.dll" "$RELEA/Binaries" 
                    
      - uses: actions/upload-artifact@v2
        with:
          name: Konclude-v0.6.2-966-Windows-x64-MSVC-Dynamic-Qt5.15.2
          path: Release          
          
          

      - name: Zip the asset into a zip file
        id: zip_asset
        run: |
          7z a -tzip Release/Konclude-v0.6.2-966-Windows-x64-MSVC-Dynamic-Qt5.15.2.zip Release/Konclude-v0.6.2-966-Windows-x64-MSVC-Dynamic-Qt5.15.2*


      - name: Upload release assets
        id: upload_assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: Release/Konclude-v0.6.2-966-Windows-x64-MSVC-Dynamic-Qt5.15.2.zip
          asset_name: Konclude-v0.6.2-966-Windows-x64-MSVC-Dynamic-Qt5.15.2.zip
          asset_content_type: application/octet-stream     
          
          

      - name: Run Examples Windows
        if: startsWith(matrix.config.os, 'windows')  
        run: | 
          $ROOT="$(pwd)"   
          $revisionCount="966"
          $revisionTagName="v0.6.2"
          $revisionHashName="fa20b125"          
          $RELEA="$ROOT/Release/Konclude-$revisionTagName-$revisionCount-Windows-x64-MSVC-Dynamic-Qt5.15.2"
          cd $RELEA
          .\Konclude.bat classification -i Tests/roberts-family-full-D.owl.xml -o roberts-family-full-class-hierarchy.owl.xml
          .\Konclude.bat satisfiability -i Tests/roberts-family-full-D.owl.xml -x http://www.co-ode.org/roberts/family-tree.owl#Aunt
          .\Konclude.bat owllinkfile -i Tests/galen-classify-request.xml -o response.xml
          .\Konclude.bat owllinkfile -i Tests/roberts-family-full-D-classify-realize-request.xml
          .\Konclude.bat owllinkfile -c Configs/default-config.xml -i Tests/1b-satisfiability-request.xml
          .\Konclude.bat sparqlfile -s Tests/lubm-univ-bench-sparql-load-and-query-test.sparql -o Tests/query-answers.xml -c Configs/querying-config.xml
          .\Konclude.bat sparqlfile -s Tests/roberts-family-full-sparql-existential-variables-query-test.sparql -i Tests/roberts-family-full-D.owl.xml
                    
