name: Build

# Run this workflow every time a new commit pushed to your repository
on: [push]

jobs:

  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest MSVC",
            os: windows-latest,
            build_type: "Release",
            cc: "cl",
            cxx: "cl"
          }   


    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Qt
        uses: jurplel/install-qt-action@v2          

      - name: Prepare Visual Studio
        if: startsWith(matrix.config.os, 'windows')
        uses: ilammy/msvc-dev-cmd@v1
        with:
          sdk: 10.0.10240.0

      - name: Compile Windows        
        if: startsWith(matrix.config.os, 'windows')
        run: |
          msbuild Konclude-VS15.sln /p:Configuration=Release /p:Platform="Win64"

      - name: Run Examples Windows
        if: startsWith(matrix.config.os, 'windows')  
        run: | 
          Release\Konclude.exe classification -i Tests/roberts-family-full-D.owl.xml -o roberts-family-full-class-hierarchy.owl.xml
          Release\Konclude.exe satisfiability -i Tests/roberts-family-full-D.owl.xml -x http://www.co-ode.org/roberts/family-tree.owl#Aunt
          Release\Konclude.exe owllinkfile -i Tests/galen-classify-request.xml -o response.xml
          Release\Konclude.exe owllinkfile -i Tests/roberts-family-full-D-classify-realize-request.xml
          Release\Konclude.exe owllinkfile -c Configs/default-config.xml -i Tests/1b-satisfiability-request.xml
          Release\Konclude.exe sparqlfile -s Tests/lubm-univ-bench-sparql-load-and-query-test.sparql -o Tests/query-answers.xml -c Configs/querying-config.xml
          Release\Konclude.exe sparqlfile -s Tests/roberts-family-full-sparql-existential-variables-query-test.sparql -i Tests/roberts-family-full-D.owl.xml
