name: Build

on: [push]

jobs:

  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu Docker",
            os: ubuntu-latest,
            build_type: "Release", 
            cc: "gcc", 
            cxx: "g++"
          }



    steps:

      - name: Prepare Directories
        run: |
          mkdir Konclude
          mkdir KoncludeDocker
          

      - name: Checkout Konclude code
        uses: actions/checkout@v2
        with:
          path: Konclude
          

      - name: Checkout Konclude Docker
        uses: actions/checkout@v2
        with:
          repository: andreas-steigmiller/KoncludeDocker
          path: KoncludeDocker

        
      - name: Build Run Image
        working-directory: KoncludeDocker
        run: | 
          ./run/snap.sh
          
        
      - name: Build Develop Image
        working-directory: KoncludeDocker
        run: | 
          ./develop/snap.sh         
  
          
      - name: Build Build Image
        working-directory: KoncludeDocker
        run: | 
          ./build/snap.sh     
    
          
      - name: Build Deploy Image
        working-directory: KoncludeDocker
        run: | 
          ./deploy/snap.sh 
          
  
      - name: Build
        working-directory: KoncludeDocker
        run: | 
          ./build_release.sh
          
          
  
      - name: Check
        run: | 
          ls -al Release
          
          
                  
      - uses: actions/upload-artifact@v2
        with:
          name: Konclude-v0.6.2-966-Linux-x64-GCC4.8.4-Static-Qt-5.13
          path: Release/Konclude-v0.6.2-966-Linux-x64-GCC4.8.4-Static-Qt-5.13
          
                    
                  
      - uses: actions/upload-artifact@v2
        with:
          name: Konclude-v0.6.2-966-Sources
          path: Release/Konclude-v0.6.2-966-Sources
                    
