name: Build

on: [push]

jobs:

  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    timeout-minutes: 600
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "macOS Latest Clang",
            os: macos-latest,
            build_type: "Release", 
            cc: "clang", 
            cxx: "clang++"
          }


    steps:
          
      - name: Checkout Konclude code
        uses: actions/checkout@v2       
        with:
          path: "konclude-static"        
    
      - name: Install Dependencies
        run: |
          brew install autoconf automake libtool
        
      - name: Prepare Environment
        run: |
          ROOT="$(pwd)"
          mkdir src
          mkdir lib
          echo $ROOT
          
      - name: Install Libxml2
        run: |
          ROOT="$(pwd)"
          # download, build and install libxml2
          cd $ROOT/src \
          && wget ftp://xmlsoft.org/libxml2/libxml2-2.9.9.tar.gz \
          && tar -xvzf libxml2-2.9.9.tar.gz \
          && mv libxml2-2.9.9 libxml2-static \
          && cd libxml2-static \
          && ./configure --without-python --prefix=$ROOT/lib/libxml2-static \
          && make \
          && make install
          
      - name: Download Qt
        run: |
          ROOT="$(pwd)"
          # download, build and install qt
          cd $ROOT/src \
          && wget -q https://download.qt.io/official_releases/qt/5.12/5.12.10/single/qt-everywhere-src-5.12.10.tar.xz \
          && tar -xJf qt-everywhere-src-5.12.10.tar.xz \
          && mv qt-everywhere-src-5.12.10 qt-static
          
      - name: Prepare Qt
        run: |
          ROOT="$(pwd)"          
          cd $ROOT/src/qt-static \
          && export MAKE=/usr/bin/make \
          && ./configure -static -prefix $ROOT/qt-static -extprefix $ROOT/lib/qt-static -no-opengl -nomake examples -nomake tests -opensource -platform macx-clang -no-icu -confirm-license -opensource
          
          
      - name: Cache Qt Compilation
        uses: actions/cache@v2
        env:
          cache-name: cache-qt-compilation
        with:
          path: src/qt-static
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('src/qt-static/makefile') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
          
          
      - name: Compile Qt
        timeout-minutes: 420
        run: |
          ROOT="$(pwd)"
          cd $ROOT/src/qt-static
          make           
          
      - name: Install Qt
        run: |
          ROOT="$(pwd)"          
          cd $ROOT/src/qt-static \
          && make install
          
          
          
