name: Build

# Run this workflow every time a new commit pushed to your repository
on: [push]

jobs:

  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu Docker",
            os: ubuntu-latest,
            build_type: "Release", 
            cc: "gcc", 
            cxx: "g++"
          }


    steps:

      - name: Prepare Directories
        run: |
          mkdir Konclude
          mkdir KoncludeDocker
          

      - name: Checkout Konclude code
        uses: actions/checkout@v2
        with:
          path: Konclude
          

      - name: Checkout Konclude Docker
        uses: actions/checkout@v2
        with:
          repository: konclude/KoncludeDocker
          path: KoncludeDocker
                    
        
      - name: Build
        working-directory: KoncludeDocker
        run: | 
          ./build_release.sh
          
