name: Build

# Run this workflow every time a new commit pushed to your repository
on: [push]

jobs:

  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:        
        - {
            name: "Ubuntu 16.04 GCC", artifact: "Linux.tar.xz",
            os: ubuntu-16.04,
            build_type: "Release", cc: "gcc", cxx: "g++"
          }


    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
          
      - name: Compile
        run: | 
          echo `gcc --version`
          echo `qmake --version`
          qmake KoncludeWithoutRedland.pro
          make -j 2          
