name: Build

on: [push]

jobs:

  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu Docker",
            os: ubuntu-latest,
            build_type: "Release", 
            cc: "gcc", 
            cxx: "g++"
          }


    steps:

      - name: Prepare Directories
        run: |
          mkdir Konclude
          mkdir KoncludeDocker
          

      - name: Checkout Konclude code
        uses: actions/checkout@v2
        with:
          path: Konclude
          

      - name: Checkout Konclude Docker
        uses: actions/checkout@v2
        with:
          repository: andreas-steigmiller/KoncludeDocker
          path: KoncludeDocker
  

      - name: Prepare Docker image caching
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        
        
      - name: Build Run Image
        working-directory: KoncludeDocker
        run: | 
          ./run/snap.sh
          
        
      - name: Build Develop Image
        working-directory: KoncludeDocker
        run: | 
          ./develop/snap.sh         
  
          
      - name: Build Build Image
        working-directory: KoncludeDocker
        run: | 
          ./build/snap.sh     
    
          
      - name: Build Deploy Image
        working-directory: KoncludeDocker
        run: | 
          ./deploy/snap.sh 
          
  
      - name: Build
        working-directory: KoncludeDocker
        run: | 
          ./build_release.sh
          
