name: Build

# Run this workflow every time a new commit pushed to your repository
on: [push]

jobs:

  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows 2016 MSVC 2017",
            os: windows-2016,
            build_type: "Release",
            cc: "cl",
            cxx: "cl"
          }   


    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Qt
        uses: jurplel/install-qt-action@v2          

      - name: Prepare Visual Studio
        if: startsWith(matrix.config.os, 'windows')
        uses: ilammy/msvc-dev-cmd@v1
        with:
          sdk: 10.0.10240.0
          

          
      - name: Environment Checking
        shell: powershell
        run: |
          Get-ChildItem Env:PATH          
          echo $PSScriptRoot
          $Env:PATH = $Env:PATH + ';D:\a\Konclude\Qt\5.15.2\msvc2019_64\bin'
          $Env:PATH = $Env:PATH + ';$PSScriptRoot\External\vcpkg\Windows\x64\bin'
          $Env:PATH = $Env:PATH + ';.\External\vcpkg\Windows\x64\bin'
          Get-ChildItem Env:PATH
          
      - name: Install Windows 8.1 SDK
        shell: powershell
        run: |
          Invoke-WebRequest -Method Get -Uri https://go.microsoft.com/fwlink/p/?LinkId=323507 -OutFile sdksetup.exe -UseBasicParsing
          Start-Process -Wait sdksetup.exe -ArgumentList "/q", "/norestart", "/features", "OptionId.WindowsDesktopSoftwareDevelopmentKit", "OptionId.NetFxSoftwareDevelopmentKit"          


      - name: Compile Windows        
        if: startsWith(matrix.config.os, 'windows')
        run: |
          msbuild Konclude-VS15.sln /p:Configuration=Release /p:Platform="Win64"


      - name: Prepare Windows Execution
        if: startsWith(matrix.config.os, 'windows')
        run: |
          Copy-Item ".\External\vcpkg\Windows\x64\bin\*" -Destination "."
          dir
          dir D:\a\Konclude\Qt\5.15.2\msvc2019_64\bin


      - name: Upload
        uses: actions/upload-artifact@v2
        if: startsWith(matrix.config.os, 'windows')  
        with:
          name: Konclude-compiled-windows
          path: x64\Release\VS2015\Konclude.exe

          

      - name: Create Konclude Release
        run: | 
          $ROOT="$(pwd)"   
          $revisionCount="966"
          $revisionTagName="v0.6.2"
          $revisionHashName="fa20b125"
          mkdir Release          
          
          $BUILD_DIR=$ROOT
          $PROJ=$ROOT
          $RELEA="$ROOT\Release\Konclude-$revisionTagName-$revisionCount-Windows-x64-MSVC-Dynamic-Qt5.15.2"
          
          mkdir $RELEA
          mkdir "$RELEA/Configs"
          mkdir "$RELEA/Tests"
          mkdir "$RELEA/Binaries"
          
          cd $BUILD_DIR
          copy "$BUILD_DIR\x64\Release\VS2015\Konclude.exe" "$RELEA/Binaries"
          
          copy "$PROJ\LGPL-3.0.txt" "$RELEA"
          copy "$PROJ\GPL.txt" "$RELEA"
          copy "$PROJ\Readme.md" "$RELEA"
          copy "$PROJ\Tests\1b-satisfiability-request.xml" "$RELEA/Tests"
          copy "$PROJ\Tests\galen.owl.xml" "$RELEA/Tests"
          copy "$PROJ\Tests\galen-classify-request.xml" "$RELEA/Tests"
          copy "$PROJ\Tests\roberts-family-full-D.owl.xml" "$RELEA/Tests"
          copy "$PROJ\Tests\roberts-family-full-D-classify-realize-request.xml" "$RELEA/Tests"
          copy "$PROJ\Tests\lubm-univ-bench.owl.xml" "$RELEA/Tests"
          copy "$PROJ\Tests\lubm-univ-bench-data-1.ttl" "$RELEA/Tests"
          copy "$PROJ\Tests\lubm-univ-bench-sparql-load-and-query-test.sparql" "$RELEA/Tests"
          copy "$PROJ\Tests\lubm-univ-bench-sparql-load-and-complex-query-rasqal-test.sparql" "$RELEA/Tests"
          copy "$PROJ\Tests\roberts-family-full-sparql-existential-variables-query-test.sparql" "$RELEA/Tests"
          copy "$PROJ\Tests\test-request.xml" "$RELEA/Tests"
          copy "$PROJ\Scripts\Konclude.bat" "$RELEA"
          copy "$PROJ\Configs\default-config.xml" "$RELEA/Configs"
          copy "$PROJ\Configs\querying-config.xml" "$RELEA/Configs"          
                    
      - uses: actions/upload-artifact@v2
        with:
          name: Konclude-v0.6.2-966-Windows-x64-MSVC-Dynamic-Qt5.15.2
          path: Release          
          

      - name: Run Examples Windows
        if: startsWith(matrix.config.os, 'windows')  
        run: | 
          $ROOT="$(pwd)"   
          $revisionCount="966"
          $revisionTagName="v0.6.2"
          $revisionHashName="fa20b125"          
          $RELEA="$ROOT/Release/Konclude-$revisionTagName-$revisionCount-Windows-x64-MSVC-Dynamic-Qt5.15.2"
          cd $RELEA
          Konclude classification -i Tests/roberts-family-full-D.owl.xml -o roberts-family-full-class-hierarchy.owl.xml
          Konclude satisfiability -i Tests/roberts-family-full-D.owl.xml -x http://www.co-ode.org/roberts/family-tree.owl#Aunt
          Konclude owllinkfile -i Tests/galen-classify-request.xml -o response.xml
          Konclude owllinkfile -i Tests/roberts-family-full-D-classify-realize-request.xml
          Konclude owllinkfile -c Configs/default-config.xml -i Tests/1b-satisfiability-request.xml
          Konclude sparqlfile -s Tests/lubm-univ-bench-sparql-load-and-query-test.sparql -o Tests/query-answers.xml -c Configs/querying-config.xml
          Konclude sparqlfile -s Tests/roberts-family-full-sparql-existential-variables-query-test.sparql -i Tests/roberts-family-full-D.owl.xml
                    
